import type { Metadata } from "next";
import { Abril_Fatface } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

import Header from "@/components/AppHeader";
import Script from "next/script";

const abrilFatface = Abril_Fatface({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// JSON-LD data for Schema.org
const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "",
  description: "",
  url: "",
  logo: "",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          id="schema-org-organization"
          type="application/ld+json"
          strategy="beforeInteractive" // Load early for SEO benefits
        >
          {JSON.stringify(organizationSchema)}
        </Script>
      </head>
      
      <body
        className={`antialiased flex flex-col  gap-8 ${abrilFatface.className} `}
      >
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
